Update static.yml

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -34,6 +34,10 @@ jobs:
         env:
           API_KEY: ${{ secrets.VITE_API_KEY }}
         run: |
+          if [ -z "$API_KEY" ]; then
+            echo "Error VITE_API_KEY is empty"
+            exit 1
+          fi
           node -e "const fs = require('fs'); let content = fs.readFileSync('index.html', 'utf8'); content = content.replace('import.meta.env.VITE_API_KEY', \"'\" + process.env.API_KEY + \"'\"); fs.writeFileSync('index.html', content);"
 
       - name: Setup Pages
